/**
 * Error codes for security-related operations
 */
export const SecurityErrorCodes = {
  // Pairing errors
  PAIRING_TOKEN_REQUIRED: 'PAIRING_TOKEN_REQUIRED',
  INVALID_PAIRING_TOKEN: 'INVALID_PAIRING_TOKEN',
  INVALID_PAIRING_SECRET: 'INVALID_PAIRING_SECRET',
  CLIENT_PUBLIC_KEY_REQUIRED: 'CLIENT_PUBLIC_KEY_REQUIRED',
  CLIENT_ALREADY_PAIRED: 'CLIENT_ALREADY_PAIRED',
  MISSING_CLIENT_PUBLIC_KEY: 'MISSING_CLIENT_PUBLIC_KEY',
  NO_PENDING_PAIRING: 'NO_PENDING_PAIRING',
  CLIENT_KEY_MISMATCH: 'CLIENT_KEY_MISMATCH',

  // Handshake errors
  NATIVE_MESSAGING_DISABLED: 'NATIVE_MESSAGING_DISABLED',
  NOT_PAIRED: 'NOT_PAIRED',
  CLIENT_NOT_PAIRED: 'CLIENT_NOT_PAIRED',
  MISSING_EPHEMERAL_PUBLIC_KEY: 'MISSING_EPHEMERAL_PUBLIC_KEY',
  MISSING_SESSION_ID: 'MISSING_SESSION_ID',
  MISSING_CLIENT_SIGNATURE: 'MISSING_CLIENT_SIGNATURE',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  IDENTITY_KEYS_UNAVAILABLE: 'IDENTITY_KEYS_UNAVAILABLE',

  // Validation errors
  INVALID_CLIENT_PUBLIC_KEY: 'INVALID_CLIENT_PUBLIC_KEY',
  INVALID_CLIENT_SIGNATURE: 'INVALID_CLIENT_SIGNATURE',
  INVALID_TRANSCRIPT: 'INVALID_TRANSCRIPT',
  CLIENT_SIGNATURE_INVALID: 'CLIENT_SIGNATURE_INVALID',

  // Secure request errors
  INVALID_SECURE_PAYLOAD: 'INVALID_SECURE_PAYLOAD',
  CLIENT_NOT_VERIFIED: 'CLIENT_NOT_VERIFIED',
  DECRYPT_FAILED: 'DECRYPT_FAILED',
  INVALID_SEQ: 'INVALID_SEQ',
  REPLAY_DETECTED: 'REPLAY_DETECTED',

  // Method registry errors
  UNKNOWN_METHOD: 'UNKNOWN_METHOD',
  DESKTOP_NOT_AUTHENTICATED: 'DESKTOP_NOT_AUTHENTICATED',

  // Auto lock errors
  MISSING_AUTO_LOCK_TIMEOUT_MS: 'MISSING_AUTO_LOCK_TIMEOUT_MS',
  INVALID_AUTO_LOCK_ENABLED: 'INVALID_AUTO_LOCK_ENABLED'
}
