export const LOWER_CASE = 'abcdefghijklmnopqrstuvwxyz'
export const UPPER_CASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
export const DIGITS = '0123456789'
export const SPECIAL_CHARS = '!@#$%^&*()_+[]{}|;:,.<>?'
export const PASSPHRASE_WORD_LIST = [
  'guitar',
  'moon',
  'lamp',
  'elephant',
  'keyboard',
  'piano',
  'sunshine',
  'apple',
  'car',
  'bicycle',
  'book',
  'balloon',
  'dog',
  'tree',
  'camera',
  'pencil',
  'cat',
  'river',
  'pizza',
  'orange',
  'watch',
  'chair',
  'icecream',
  'robot',
  'mango',
  'jacket',
  'phone',
  'house',
  'computer',
  'plum',
  'star',
  'glove',
  'mountain',
  'guava',
  'lemon',
  'grape',
  'window'
]
