'use strict'

const { test, expect } = require('../fixtures/app.runner')
const { LoginPage, VaultSelectPage, MainView, CreateLoginPage } = require('../components')
const testData = require('../fixtures/test-data')

test.describe('Password', () => {
  test.describe.configure({ mode: 'serial' })

  let loginPage, vaultSelectPage, mainView, createLoginPage, page

  test.beforeAll(async ({ app }) => {
    page = app.page
    loginPage = new LoginPage(page.locator('body'))
    vaultSelectPage = new VaultSelectPage(page.locator('body'))
    mainView = new MainView(page.locator('body'))
    createLoginPage = new CreateLoginPage(page.locator('body'))
  })

  test.afterAll(async ({ app }) => {
    await mainView.deleteElementFromViewMode()
  })

  test('Password fields value generated by the app is inserted into "Password" field', async ({ page }) => {

    await test.step('LOGIN', async () => {
      await expect(loginPage.title).toHaveText('Enter your Master password')
      await loginPage.login(testData.credentials.validPassword)
    })

    await test.step('VAULT SELECTION', async () => {
      await expect(vaultSelectPage.title).toHaveText('Select a vault, create a new one or load another one')
      await vaultSelectPage.selectVault(testData.vault.name)
    })

    await test.step('CREATE LOGIN ELEMENT - INITIAL', async () => {
      await mainView.selectSideBarCategory('login')
      await mainView.clickCreateNewElementButton('Create a login')
      await createLoginPage.createLoginElementInsertData('Login Title', 'Test User', 'Test Pass', 'www.website.co', 'Test Note')
      await createLoginPage.clickSave()
      await mainView.verifyElement('Login Title')
    })

    await test.step('OPEN/EDIT ELEMENT', async () => {
      await mainView.openElement()
      await mainView.editElement()
    })

    /**
   * @qase.id PAS-566
   * @description Password fields value generated by the app is inserted into "Password" field after clicking on "Insert password" button
   */
    await test.step('OPEN PASSWORD MENU', async () => {
      await createLoginPage.openPasswordMenu()
    })

    await test.step('CLICK INSERT PASSWORD BUTTON FROM PASSWORD MENU', async () => {
      await createLoginPage.clickInsertPasswordButton()
    })

    await test.step('SHOW PASSWORD AND VERIFY PASSWORD VALUE HAS CHANGED', async () => {
      await createLoginPage.clickShowHidePasswordButton()
      await createLoginPage.verifyPasswordToNotHaveValue('Test Password')
    })

    await test.step('CLICK CLOSE (X) BUTTON', async () => {
      await createLoginPage.clickElementItemCloseButton()
    })

  })

  // ### This test will be uncomment after adding selector id's ###

  // test('Password menu verification', async ({ page }) => {

  //   await test.step('LOGIN', async () => {
  //     await expect(loginPage.title).toHaveText('Enter your Master password')
  //     await loginPage.login(testData.credentials.validPassword)
  //   })

  //   await test.step('VAULT SELECTION', async () => {
  //     await expect(vaultSelectPage.title).toHaveText('Select a vault, create a new one or load another one')
  //     await vaultSelectPage.selectVault(testData.vault.name)
  //   })

  //   await test.step('OPEN LOGIN ELEMENT AND VERIFY PASSWORD MENU OPTIONS', async () => {
  //     await mainView.openElement()
  //     await mainView.editElement()
  //     await createLoginPage.openPasswordMenu()
  //     await createLoginPage.verifyPasswordTypeRadioButtonState('active')
  //     await createLoginPage.verifyPassphraseTypeRadioButtonState('inactive')
  //     await createLoginPage.verifyCharSliderIsVisible()
  //     await createLoginPage.verifyspecialCharacterSwitcherState('on')

  //   })

  //   await test.step('Exit to login screen', async () => {
  //     await createLoginPage.clickElementItemCloseButton()
  //   })

  //   await test.step('Exit to login screen', async () => {
  //     await createLoginPage.clickElementItemCloseButton()
  //   })

  //   await test.step('Exit to login screen', async () => {
  //     await mainView.clickSidebarExitButton()
  //   })

  // })

})
