import { test, expect } from '../../fixtures/app.runner.js';
import {
  LoginPage,
  VaultSelectPage,
  MainPage,
  SideMenuPage,
  CreateOrEditPage,
  Utilities,
  DetailsPage
} from '../../components/index.js';
import testData from '../../fixtures/test-data.js';

test.describe('Password', () => {
  test.describe.configure({ mode: 'serial' })

  let loginPage, vaultSelectPage, createOrEditPage, sideMenuPage, mainPage, utilities, detailsPage, page

  test.beforeEach(async ({ app }) => {
    page = await app.getPage()
    const root = page.locator('body')
    loginPage = new LoginPage(root)
    vaultSelectPage = new VaultSelectPage(root)
    mainPage = new MainPage(root)
    sideMenuPage = new SideMenuPage(root)
    createOrEditPage = new CreateOrEditPage(root)
    utilities = new Utilities(root)
    detailsPage = new DetailsPage(root)

    // await loginPage.loginToApplication(testData.credentials.validPassword)
    // await vaultSelectPage.selectVaultbyName(testData.vault.name)
  })

  test.afterAll(async ({ }) => {
    await utilities.deleteAllElements()
    await sideMenuPage.clickSidebarExitButton()
  })

  test('Login to application', async ({ page }) => {
    await loginPage.loginToApplication(testData.credentials.validPassword)
    await vaultSelectPage.selectVaultbyName(testData.vault.name)
  })

  test('Password fields value generated by the app is inserted into "Password" field', async ({ page }) => {

    await test.step('CREATE LOGIN ELEMENT - initial empty element collection', async () => {
      await sideMenuPage.selectSideBarCategory('login')
      await utilities.deleteAllElements()
      await mainPage.clickCreateNewElementButton('Create a login')

      await createOrEditPage.fillCreateOrEditInput('title', 'Login Title')

      await createOrEditPage.fillCreateOrEditInput('username', 'Test User')
      await createOrEditPage.fillCreateOrEditInput('password', 'Test Pass')
      await createOrEditPage.fillCreateOrEditInput('website', 'https://www.website.co')
      await createOrEditPage.fillCreateOrEditInput('note', 'Test Note')

      await createOrEditPage.clickOnCreateOrEditButton('save')
      await page.waitForTimeout(testData.timeouts.action)

    })

    await test.step('OPEN ELEMENT', async () => {
      await mainPage.openElementDetails()
    })

    await test.step('EDIT ELEMENT DETAILS', async () => {
      await detailsPage.editElement()
    })

    /**
   * @qase.id PAS-XXXX
   * @description Password fields value generated by the app is inserted into "Password" field after clicking on "Insert password" button
   */
    await test.step('OPEN PASSWORD MENU', async () => {
      await createOrEditPage.openPasswordMenu()
    })

    await test.step('CLICK INSERT PASSWORD BUTTON FROM PASSWORD MENU', async () => {
      await createOrEditPage.clickInsertPasswordButton()
    })

    await test.step('SHOW PASSWORD AND VERIFY PASSWORD VALUE HAS CHANGED', async () => {
      await createOrEditPage.clickShowHidePasswordButtonLast()
      await createOrEditPage.verifyPasswordToNotHaveValue('Test Password')
    })

    await test.step('CLICK CLOSE (X) BUTTON', async () => {
      await createOrEditPage.clickElementItemCloseButton()
    })

    await test.step('VERIFY PASSWORD MENU OPTIONS', async () => {
      await detailsPage.editElement()
      await createOrEditPage.openPasswordMenu()

      await createOrEditPage.verifyRadioButtonPasswordState('active')
      await createOrEditPage.verifyRadioButtonPassphraseState('inactive')
      await createOrEditPage.verifyCharsliderByPositionNumber('8')
      await createOrEditPage.verifySpecialCharactersSwitchByState('on')
      await createOrEditPage.verifyPasswordStrenght('success', 'success', 'Safe')

      await createOrEditPage.clickSwitchByState('on')

      await createOrEditPage.verifySpecialCharactersSwitchByState('off')
      await createOrEditPage.verifyPasswordStrenght('warning', 'warning', 'Weak')

      await createOrEditPage.clickSwitchByState('off')

      await createOrEditPage.verifySpecialCharactersSwitchByState('on')
      await createOrEditPage.verifyPasswordStrenght('success', 'success', 'Safe')

    })

    await test.step('CLICK CLOSE (X) BUTTON', async () => {
      await createOrEditPage.clickElementItemCloseButton()
    })

    await test.step('CLICK CLOSE (X) BUTTON', async () => {
      await createOrEditPage.clickElementItemCloseButton()
    })

  })

})
